=== mohamedniang/tp_xml_07_04_2022/cour.dtd
<!ELEMENT cour (
  descriptionCour,
  renseignementEnseignant,
  infoLieuHoraire
)>
<!ELEMENT descriptionCour (
  intitule,
  uniteEnseignement,
  chargeTravail,
  semestre,
  niveau,
  prerequis
)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT uniteEnseignement (#PCDATA)>
<!ELEMENT chargeTravail (
  credit,
  coeficient,
  volumeHoraire
)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT coeficient (#PCDATA)>
<!ELEMENT volumeHoraire (#PCDATA)>
<!ELEMENT semestre (#PCDATA)>
<!ELEMENT niveau (#PCDATA)>
<!ELEMENT prerequis (#PCDATA)>
<!ELEMENT renseignementEnseignant (
  enseignant+
)>
<!ELEMENT enseignant (
  prenom,
  nom,
  adresse,
  courriel,
  heures
)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT courriel (#PCDATA)>
<!ELEMENT heures (#PCDATA)>
<!ATTLIST renseignementEnseignant nombre CDATA #REQUIRED>
<!ELEMENT infoLieuHoraire (
  salleCour,
  heureDebut,
  heureFin
)>
<!ELEMENT salleCour (#PCDATA)>
<!ELEMENT heureDebut (#PCDATA)>
<!ELEMENT heureFin (#PCDATA)>

=== mohamedniang/tp_xml_07_04_2022/cour.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE cour SYSTEM "cour.dtd"> -->

<cour xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cour.xsd">
  <descriptionCour>
    <intitule>
      Algorithmique et Programmation 2
    </intitule>
    <uniteEnseignement>
      Informatique INF 123
    </uniteEnseignement>
    <chargeTravail>
      <credit>8</credit>
      <coeficient>3</coeficient>
      <volumeHoraire>40</volumeHoraire>
    </chargeTravail>
    <semestre>2</semestre>
    <niveau>Licence 1</niveau>
    <prerequis>
      Algorithmique et Programmation 1
    </prerequis>
  </descriptionCour>
  <renseignementEnseignant nombre="1">
    <enseignant>
      <prenom>Alioune</prenom>
      <nom>Ndoye</nom>
      <adresse>UFR SET près de la scolarité</adresse>
      <courriel>ndoyealioune@univ-thies.sn</courriel>
      <heures>8-17</heures>
    </enseignant>
  </renseignementEnseignant>
  <infoLieuHoraire>
    <salleCour>5</salleCour>
    <heureDebut>09:00:00</heureDebut>
    <heureFin>12:00:00</heureFin>
  </infoLieuHoraire>
</cour>
